name: Create and Cache Pixi Lock
description: Generate a pixi.lock file and cache it for use by other jobs.

inputs:
  pixi-version:
    description: "Version of pixi to use for generating the lock file"
    required: false
    default: "latest"
  hash-files:
    description: "Files to use to generate the hash key for the lock file."
    required: false
    default: |
      pixi.toml
      pyproject.toml
  manifest-path:
    required: false
    description: >-
      Path to the manifest file (i.e., `pixi.toml`) to use for the pixi CLI. Defaults to `pixi.toml`, falling back to `pyproject.toml`.

outputs:
  pixi-version:
    description: "The pixi version used (for passing to downstream jobs)"
    value: ${{ inputs.pixi-version }}
  cache-key:
    description: "The cache key used"
    value: ${{ steps.cache-key.outputs.key }}

runs:
  using: "composite"
  steps:
    - name: Get cache key
      id: cache-key
      shell: bash
      env:
        PIXI_VERSION: ${{ inputs.pixi-version }}
        HASH_FILES: ${{ hashFiles(inputs.hash-files) }}
      run: |
        today=$(date +'%Y-%m-%d')
        key="pixi-lock_${PIXI_VERSION}_${HASH_FILES}_${today}"
        echo "key=${key}" >> "$GITHUB_OUTPUT"

    - name: Find manifest and lock paths path
      id: meta
      shell: bash
      env:
        MANIFEST_PATH: ${{ inputs.manifest-path }}
      run: |
        if [[ -n "$MANIFEST_PATH" ]]; then
          manifest_path="$MANIFEST_PATH"
        elif [[ -f "pixi.toml" ]]; then
          manifest_path="pixi.toml"
        elif [[ -f "pyproject.toml" ]]; then
          manifest_path="pyproject.toml"
        else
          echo "Error: no manifest file found (pixi.toml or pyproject.toml)" >&2
          exit 1
        fi
        echo "manifest-path=${manifest_path}" >> "$GITHUB_OUTPUT"
        echo "lock-path=$(dirname "${manifest_path}")/pixi.lock" >> "$GITHUB_OUTPUT"

    - name: Restore pixi.lock from cache
      uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      id: restore
      with:
        path: pixi.lock
        key: ${{ steps.cache-key.outputs.key }}
        enableCrossOsArchive: true

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
      if: ${{ !steps.restore.outputs.cache-hit }}
      with:
        pixi-version: ${{ inputs.pixi-version }}
        run-install: false
        manifest-path: ${{ steps.meta.outputs.manifest-path }}

    - name: Run pixi lock
      if: ${{ !steps.restore.outputs.cache-hit }}
      shell: bash
      env:
        MANIFEST_PATH: ${{ steps.meta.outputs.manifest-path }}
      run: pixi lock --manifest-path=$MANIFEST_PATH

    - name: Save pixi.lock to cache
      uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      if: ${{ !steps.restore.outputs.cache-hit }}
      with:
        path: ${{ steps.meta.outputs.lock-path }}
        key: ${{ steps.cache-key.outputs.key }}
        enableCrossOsArchive: true
