name: Restore Pixi Lock
description: Restore a previously cached pixi.lock file.

inputs:
  cache-key:
    description: "The cache key from create-and-cache"
    required: true
  fallback-key:
    description: "The fallback cache key from create-and-cache (for midnight edge cases)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore pixi.lock from cache
      uses: actions/cache/restore@v5
      id: restore
      with:
        path: pixi.lock
        key: ${{ inputs.cache-key }}
        restore-keys: |
          ${{ inputs.fallback-key }}
        fail-on-cache-miss: true
